using System;
using System.Collections.Generic;
using System.Text;

namespace WorldFactbookIndexer
{
    public class Country
    {
        public String Code { get; set; }
        public String Name { get; set; }

        // Return key that matches JSON key in list of country objects.
        // Calculated as lower-case edition of name, with commas+parentheses removed and spaces+hyphens replaced with underscores

        public String Key
        {
            get
            {
                if (String.IsNullOrEmpty(Name))
                    return this.Name;
                else
                    return this.Name.Replace(",","").Replace("(","").Replace(")","").Replace("-","_").Replace(" ", "_").ToLower();
            }
        }

        public Country() { }
        public Country(String code, String name)
        {
            this.Code = code;
            this.Name = name;
        }

        // List - return country list.

        public static Country[] List()
        {
            return new Country[]
            {
                new Country("xx", "World"),
                new Country("af", "Afghanistan"),
                new Country("ax", "Akrotiri"),
                new Country("al", "Albania"),
                new Country("ag", "Algeria"),
                new Country("aq", "American Samoa"),
                new Country("an", "Andorra"),
                new Country("ao", "Angola"),
                new Country("av", "Anguilla"),
                new Country("ay", "Antarctica"),
                new Country("ac", "Antigua And Barbuda"),
                new Country("xq", "Arctic Ocean"),
                new Country("ar", "Argentina"),
                new Country("am", "Armenia"),
                new Country("aa", "Aruba"),
                new Country("at", "Ashmore And Cartier Islands"),
                new Country("zh", "Atlantic Ocean"),
                new Country("as", "Australia"),
                new Country("au", "Austria"),
                new Country("aj", "Azerbaijan"),
                new Country("bf", "Bahamas, The"),
                new Country("ba", "Bahrain"),
                new Country("bg", "Bangladesh"),
                new Country("bb", "Barbados"),
                new Country("bo", "Belarus"),
                new Country("be", "Belgium"),
                new Country("bh", "Belize"),
                new Country("bn", "Benin"),
                new Country("bd", "Bermuda"),
                new Country("bt", "Bhutan"),
                new Country("bl", "Bolivia"),
                new Country("bk", "Bosnia And Herzegovina"),
                new Country("bc", "Botswana"),
                new Country("bv", "Bouvet Island"),
                new Country("br", "Brazil"),
                new Country("io", "British Indian Ocean Territory"),
                new Country("vi", "British Virgin Islands"),
                new Country("bx", "Brunei"),
                new Country("bu", "Bulgaria"),
                new Country("uv", "Burkina Faso"),
                new Country("bm", "Burma"),
                new Country("by", "Burundi"),
                new Country("cv", "Cabo Verde"),
                new Country("cb", "Cambodia"),
                new Country("cm", "Cameroon"),
                new Country("ca", "Canada"),
                new Country("cj", "Cayman Islands"),
                new Country("ct", "Central African Republic"),
                new Country("cd", "Chad"),
                new Country("ci", "Chile"),
                new Country("ch", "China"),
                new Country("kt", "Christmas Island"),
                new Country("ip", "Clipperton Island"),
                new Country("ck", "Cocos (Keeling) Islands"),
                new Country("co", "Colombia"),
                new Country("cn", "Comoros"),
                new Country("cg", "Congo, Democratic Republic Of The"),
                new Country("cf", "Congo, Republic Of The"),
                new Country("cw", "Cook Islands"),
                new Country("cr", "Coral Sea Islands"),
                new Country("cs", "Costa Rica"),
                new Country("iv", "Cote D'Ivoire"),
                new Country("hr", "Croatia"),
                new Country("cu", "Cuba"),
                new Country("uc", "Curacao"),
                new Country("cy", "Cyprus"),
                new Country("ez", "Czechia"),
                new Country("da", "Denmark"),
                new Country("dx", "Dhekelia"),
                new Country("dj", "Djibouti"),
                new Country("do", "Dominica"),
                new Country("dr", "Dominican Republic"),
                new Country("ec", "Ecuador"),
                new Country("eg", "Egypt"),
                new Country("es", "El Salvador"),
                new Country("ek", "Equatorial Guinea"),
                new Country("er", "Eritrea"),
                new Country("en", "Estonia"),
                new Country("wz", "Eswatini"),
                new Country("et", "Ethiopia"),
                new Country("fk", "Falkland Islands (Islas Malvinas)"),
                new Country("fo", "Faroe Islands"),
                new Country("fj", "Fiji"),
                new Country("fi", "Finland"),
                new Country("fr", "France"),
                new Country("fp", "French Polynesia"),
                new Country("gb", "Gabon"),
                new Country("ga", "Gambia, The"),
                new Country("gz", "Gaza Strip"),
                new Country("gg", "Georgia"),
                new Country("gm", "Germany"),
                new Country("gh", "Ghana"),
                new Country("gi", "Gibraltar"),
                new Country("gr", "Greece"),
                new Country("gl", "Greenland"),
                new Country("gj", "Grenada"),
                new Country("gq", "Guam"),
                new Country("gt", "Guatemala"),
                new Country("gk", "Guernsey"),
                new Country("gv", "Guinea"),
                new Country("pu", "Guinea-Bissau"),
                new Country("gy", "Guyana"),
                new Country("ha", "Haiti"),
                new Country("hm", "Heard Island And Mcdonald Islands"),
                new Country("vt", "Holy See (Vatican City)"),
                new Country("ho", "Honduras"),
                new Country("hk", "Hong Kong"),
                new Country("hu", "Hungary"),
                new Country("ic", "Iceland"),
                new Country("in", "India"),
                new Country("xo", "Indian Ocean"),
                new Country("id", "Indonesia"),
                new Country("ir", "Iran"),
                new Country("iz", "Iraq"),
                new Country("ei", "Ireland"),
                new Country("im", "Isle Of Man"),
                new Country("is", "Israel"),
                new Country("it", "Italy"),
                new Country("jm", "Jamaica"),
                new Country("jn", "Jan Mayen"),
                new Country("ja", "Japan"),
                new Country("je", "Jersey"),
                new Country("jo", "Jordan"),
                new Country("kz", "Kazakhstan"),
                new Country("ke", "Kenya"),
                new Country("kr", "Kiribati"),
                new Country("kn", "Korea, North"),
                new Country("ks", "Korea, South"),
                new Country("kv", "Kosovo"),
                new Country("ku", "Kuwait"),
                new Country("kg", "Kyrgyzstan"),
                new Country("la", "Laos"),
                new Country("lg", "Latvia"),
                new Country("le", "Lebanon"),
                new Country("lt", "Lesotho"),
                new Country("li", "Liberia"),
                new Country("ly", "Libya"),
                new Country("ls", "Liechtenstein"),
                new Country("lh", "Lithuania"),
                new Country("lu", "Luxembourg"),
                new Country("mc", "Macau"),
                new Country("mk", "Macedonia"),
                new Country("ma", "Madagascar"),
                new Country("mi", "Malawi"),
                new Country("my", "Malaysia"),
                new Country("mv", "Maldives"),
                new Country("ml", "Mali"),
                new Country("mt", "Malta"),
                new Country("rm", "Marshall Islands"),
                new Country("mr", "Mauritania"),
                new Country("mp", "Mauritius"),
                new Country("mx", "Mexico"),
                new Country("fm", "Micronesia, Federated States Of"),
                new Country("md", "Moldova"),
                new Country("mn", "Monaco"),
                new Country("mg", "Mongolia"),
                new Country("mj", "Montenegro"),
                new Country("mh", "Montserrat"),
                new Country("mo", "Morocco"),
                new Country("mz", "Mozambique"),
                new Country("wa", "Namibia"),
                new Country("nr", "Nauru"),
                new Country("bq", "Navassa Island"),
                new Country("np", "Nepal"),
                new Country("nl", "Netherlands"),
                new Country("nc", "New Caledonia"),
                new Country("nz", "New Zealand"),
                new Country("nu", "Nicaragua"),
                new Country("ng", "Niger"),
                new Country("ni", "Nigeria"),
                new Country("ne", "Niue"),
                new Country("nf", "Norfolk Island"),
                new Country("cq", "Northern Mariana Islands"),
                new Country("no", "Norway"),
                new Country("mu", "Oman"),
                new Country("zn", "Pacific Ocean"),
                new Country("pk", "Pakistan"),
                new Country("ps", "Palau"),
                new Country("um", "Palmyra Atoll"),
                new Country("pm", "Panama"),
                new Country("pp", "Papua New Guinea"),
                new Country("pf", "Paracel Islands"),
                new Country("pa", "Paraguay"),
                new Country("pe", "Peru"),
                new Country("rp", "Philippines"),
                new Country("pc", "Pitcairn Islands"),
                new Country("pl", "Poland"),
                new Country("po", "Portugal"),
                new Country("rq", "Puerto Rico"),
                new Country("qa", "Qatar"),
                new Country("ro", "Romania"),
                new Country("rs", "Russia"),
                new Country("rw", "Rwanda"),
                new Country("tb", "Saint Barthelemy"),
                new Country("sh", "Saint Helena, Ascension, And Tristan Da Cunha"),
                new Country("sc", "Saint Kitts And Nevis"),
                new Country("st", "Saint Lucia"),
                new Country("rn", "Saint Martin"),
                new Country("sb", "Saint Pierre And Miquelon"),
                new Country("vc", "Saint Vincent And The Grenadines"),
                new Country("ws", "Samoa"),
                new Country("sm", "San Marino"),
                new Country("tp", "Sao Tome And Principe"),
                new Country("sa", "Saudi Arabia"),
                new Country("sg", "Senegal"),
                new Country("ri", "Serbia"),
                new Country("se", "Seychelles"),
                new Country("sl", "Sierra Leone"),
                new Country("sn", "Singapore"),
                new Country("nn", "Sint Maarten"),
                new Country("lo", "Slovakia"),
                new Country("si", "Slovenia"),
                new Country("bp", "Solomon Islands"),
                new Country("so", "Somalia"),
                new Country("sf", "South Africa"),
                new Country("sx", "South Georgia And South Sandwich Islands"),
                new Country("od", "South Sudan"),
                new Country("oo", "Southern Ocean"),
                new Country("sp", "Spain"),
                new Country("pg", "Spratly Islands"),
                new Country("ce", "Sri Lanka"),
                new Country("su", "Sudan"),
                new Country("ns", "Suriname"),
                new Country("sv", "Svalbard"),
                new Country("sw", "Sweden"),
                new Country("sz", "Switzerland"),
                new Country("sy", "Syria"),
                new Country("tw", "Taiwan"),
                new Country("ti", "Tajikistan"),
                new Country("tz", "Tanzania"),
                new Country("th", "Thailand"),
                new Country("tt", "Timor-Leste"),
                new Country("to", "Togo"),
                new Country("tl", "Tokelau"),
                new Country("tn", "Tonga"),
                new Country("td", "Trinidad And Tobago"),
                new Country("ts", "Tunisia"),
                new Country("tu", "Turkey"),
                new Country("tx", "Turkmenistan"),
                new Country("tk", "Turks And Caicos Islands"),
                new Country("tv", "Tuvalu"),
                new Country("ug", "Uganda"),
                new Country("up", "Ukraine"),
                new Country("ae", "United Arab Emirates"),
                new Country("uk", "United Kingdom"),
                new Country("us", "United States"),
                new Country("uy", "Uruguay"),
                new Country("uz", "Uzbekistan"),
                new Country("nh", "Vanuatu"),
                new Country("ve", "Venezuela"),
                new Country("vm", "Vietnam"),
                new Country("vq", "Virgin Islands"),
                new Country("wq", "Wake Island"),
                new Country("wf", "Wallis And Futuna"),
                new Country("we", "West Bank"),
                new Country("wi", "Western Sahara"),
                new Country("ym", "Yemen"),
                new Country("za", "Zambia"),
                new Country("zi", "Zimbabwe"),
                new Country("ee", "European Union")
            };
        }
    }
}
